# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_sacII_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_sacII_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_sacII_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_sacII_rcpparma_bothproducts`, x)
}

triu <- function(m, n) {
    .Call(`_sacII_triu`, m, n)
}

tril <- function(m, n) {
    .Call(`_sacII_tril`, m, n)
}

colProds <- function(m) {
    .Call(`_sacII_colProds`, m)
}

count_pi_mat <- function(S, i, params, constant) {
    .Call(`_sacII_count_pi_mat`, S, i, params, constant)
}

count_pi_double <- function(S, i, params, constant) {
    .Call(`_sacII_count_pi_double`, S, i, params, constant)
}

count_p <- function(i, params, constant) {
    .Call(`_sacII_count_p`, i, params, constant)
}

count_m <- function(i, params, constant) {
    .Call(`_sacII_count_m`, i, params, constant)
}

count_log_like <- function(first_record_data, params, constant) {
    .Call(`_sacII_count_log_like`, first_record_data, params, constant)
}

